ietf-wg-add/draft-ietf-add-ddr

README.md
Please don't merge until after Sunday.  Pull request is a test of the Sunday summary.
=> Corrected link to contributing info

draft-ietf-add-ddr.md
This addresses the remaining portions of #7 not address by a prior PR
=> clarified SUDN is to be treated as an SUDN in the spirit of RFC8880

draft-ietf-add-ddr.md
=> Suggest re-sending the DDR query

draft-ietf-add-ddr.md
=> Explain that clients can always use the DDR hint

draft-ietf-add-ddr.md
=> SvcDomainName -> TargetName

draft-ietf-add-ddr.md
=> Make ESNI reference in appendix informative

draft-ietf-add-ddr.md
=> Updated dependency on SVCB DNS draft to the ADD adopted version

draft-ietf-add-ddr.md
=> Rename "authenticated" to "verified"

draft-ietf-add-ddr.md
=> Add security consideration about dohpath attacks

draft-ietf-add-ddr.md
=> Clients should ignore SVCB records when they do not understand all of its mandatory parameters

draft-ietf-add-ddr.md
=> Explain relationship with DNR

draft-ietf-add-ddr.md
=> No such thing as a SVCB packet

draft-ietf-add-ddr.md
There's a lot of redundancy in this draft, but this might help.
=> Just cite Section 5 of SVCB

draft-ietf-add-ddr.md
=> Explain that trust anchors are checked, in addition to the SAN

draft-ietf-add-ddr.md
Addressing the comments in #73
=> Addressing the feedback provided by Thomas Fossati

draft-ietf-add-ddr.md
=> Clarify dohpath manipulation attack

draft-ietf-add-ddr.md
=> Reference SVCB-DNS text about SVCB-reliant

draft-ietf-add-ddr.md
=> Addressing comments by Roman Danyliw

draft-ietf-add-ddr.md
This review does NOT close the issue; it only addresses the "easier" items. 
The harder, normative challenging comments may be tackled together with overlapping feedback from other reviewers such as Ben.
=> addressing the less major items from review by Robert

draft-ietf-add-ddr.md
=> Nits and IANA text changes from John

draft-ietf-add-ddr.md
=> making address family support normative and clearifying definition for Unencrypted Resolver

draft-ietf-add-ddr.md
=> corrected SVCB example with equal priorities

draft-ietf-add-ddr.md
=> Changed resolver terminology and some word choices

draft-ietf-add-ddr.md
=> Added Domain Name Reservation Considerations section

draft-ietf-add-ddr.md
=> Add more explanations for SHOULDs

draft-ietf-add-ddr.md
=> Address Paul's review

draft-ietf-add-ddr.md
=> Clarify which IP address is used as the host

draft-ietf-add-ddr.md
=> Clarification in intro

draft-ietf-add-ddr.md
=> Address Ben's review
